# Generated by Django 3.0.6 on 2020-05-18 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200518_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 21, 52, 13, 846107, tzinfo=utc)),
        ),
    ]
