# Generated by Django 3.0.6 on 2020-05-23 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200522_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 6, 45, 35, 577490, tzinfo=utc)),
        ),
    ]
